langage: cpp
dist: bionic

os:
 - linux

branches:
 only:
  - master
  
env:
 alias:
  - CONFIG=release

install:
- sudo apt-get --yes install gcc
- sudo apt-get --yes install build-essential

script:
- chmod +x QIUM.sh
